export interface ProxiesAddresses {
  PRODUCER_API_PROXY_ADDRESS: string;
  PRODUCER_NUSAGE_PROXY_ADDRESS: string;
  PRODUCER_VESTING_API_PROXY_ADDRESS: string;
  FACTORY_PROXY_ADDRESS: string;
  URI_GENERATOR_PROXY_ADDRESS: string; 
  PRODUCER_STORAGE_PROXY_ADDRESS: string;
}

export const PROXIES_ADDRESSES_FILENAME = "./PROXIES_ADDRESSES.io";
